# Generated by Django 6.0.1 on 2026-01-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proforma_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
